mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.qg24.softwareplatform.po.entity
    configuration:
        map-underscore-to-camel-case: true
server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/software_platform
    redis:
        database: 0
        url: redis://localhost:6379/0
email:
    host: smtp.qq.com
    password: ecxcdzqqmwslddcj
    username: 3087609114@qq.com
    port: 587
alioss:
    bucket-name: faken
    access-key-secret: DBHso3lWRctacim2d526P9OS4QEGvt
    access-key-id: LTAI5tRW66tNtLVeMASWo71F
    endpoint: oss-cn-guangzhou.aliyuncs.com







